<?php
/**
 * Title: Rodapé LQF
 * Slug: lqf/footer
 * Inserter: no
 */
?>
<!-- wp:group {"tagName":"div","className":"lqf-footer","layout":{"type":"default"}} --><div class="wp-block-group lqf-footer"><!-- wp:group {"tagName":"div","className":"lqf-shell lqf-footer-grid","layout":{"type":"default"}} --><div class="wp-block-group lqf-shell lqf-footer-grid"><!-- wp:group {"tagName":"div","className":"lqf-footer-brand","layout":{"type":"default"}} --><div class="wp-block-group lqf-footer-brand"><!-- wp:html {} --><a href="https://www.lqf.com.br/" class="lqf-logo lqf-logo-vertical" aria-label="LQF Farmacêutica — Início"><img src="<?php echo esc_url(get_theme_file_uri('assets/logo-vertical.webp')); ?>" alt="LQF Farmacêutica" width="1080" height="610"/></a><!-- /wp:html -->
<!-- wp:paragraph {} --><p>A ciência por trás da beleza.</p><!-- /wp:paragraph -->
</div><!-- /wp:group -->
<!-- wp:html {} --><nav class="lqf-footer-nav" aria-label="Rodapé"><a href="https://www.lqf.com.br/">Início</a><a href="https://www.lqf.com.br/sobre">Sobre</a><a href="https://www.lqf.com.br/tecnologia">Tecnologia</a><a href="https://www.lqf.com.br/produtos">Inovações</a><a href="https://www.lqf.com.br/#partners">Partners</a><a href="https://www.lqf.com.br/processo">Processo LQF</a><a href="https://www.lqf.com.br/private-label">Private Label</a><a href="https://www.lqf.com.br/contato#formulario">Contato</a><a href="https://www.lqf.com.br/politica-de-privacidade">Política de Privacidade</a></nav><!-- /wp:html -->
<!-- wp:html {} --><div class="lqf-footer-contact"><p><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg><span>Avenida Floriano Andre Cabrera, 1361<br>Cidade Jardim | CEP: 15.081-190<br>São José do Rio Preto - SP</span></p><p><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.4 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2Z"/></svg><a href="https://wa.me/5517991151770">(17) 99115-1770</a></p><p><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-9 6a2 2 0 0 1-2 0L2 7"/></svg><a href="mailto:comercial@lqf.com.br">comercial@lqf.com.br</a></p><div class="lqf-social"><a href="https://www.facebook.com/GrupoLQF/" aria-label="Facebook LQF"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg></a><a href="https://www.instagram.com/lqflaboratorio/" aria-label="Instagram LQF"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></svg></a></div></div><!-- /wp:html -->

</div><!-- /wp:group -->
<!-- wp:group {"tagName":"div","className":"lqf-shell lqf-footer-bottom","layout":{"type":"default"}} --><div class="wp-block-group lqf-shell lqf-footer-bottom"><!-- wp:paragraph {} --><p>© <?php echo esc_html(wp_date("Y")); ?> LQF Farmacêutica. Todos os direitos reservados.</p><!-- /wp:paragraph -->
<!-- wp:paragraph {} --><p><a href="https://elevenmind.com.br/">Desenvolvido por Elevenmind</a>　<a href="https://www.lqf.com.br/politica-de-privacidade">Política de Privacidade</a></p><!-- /wp:paragraph -->
</div><!-- /wp:group -->
</div><!-- /wp:group -->
